name = "namegenie-worker"
main = "src/index.js"
compatibility_date = "2025-06-01"

[vars]
DEEPSEEK_MODEL = "deepseek-chat"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "e65f790d4be94a23983a94ba31e1b220"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.kv_namespaces]
RATE_LIMIT_KV = "e65f790d4be94a23983a94ba31e1b220"
